### ISSUE TITLE
Logging guzzle requests

### ISSUE THREAD

**Issue by SDJeff** [geccomedia/weclapp#19]
Is it possible to integrate a logging to debug the json structure of the requests?
For example if you have complex variants with options the feedback of weclapp api is very poor.
To discuss with the support, they would like to see the raw json string.

**Comment by Tamrael** [comment]
@SDJeff do you need the result from the api or the query string/post data from the request? If you need the later you can use the QueryExecuted event fired in https://github.com/geccomedia/weclapp/blob/55412d76b097d17a85699a48fa501bf738a81f2a/src/Connection.php#L244-L245

For real logging I would have to get back to you with a solution next week.

**Comment by SDJeff** [comment]
@Tamrael Yes second point was the goal of my question. I will check this with the event. Thx.

**Comment by Tamrael** [comment]
@SDJeff sorry for taking so long to get back to you. I hope the events got you set up with all the data you needed at the time.

If not, have a look at #20 that is basically the same as the events but implemented in almost the same way as eloquent does it.
