### ISSUE TITLE
Usage of the Model Comment

### ISSUE THREAD

**Issue by Nigatol** [geccomedia/weclapp#22]
Hi, everybody!

I tried to handle comments in weclapp, but the usage of the model raised the following error:
`Comment::where('entityId', 3268648)->where('entityName', 'customer')->get();`

```
 Client error: `GET https://***.weclapp.com/webapp/api/v1/comment?entityId-eq=3268648&entityName-eq=customer&pageSize=100` resulted in a `400 Bad Request` response:
{
  "detail": "missing parameter: entityName",
  "error": "missing parameter: entityName",
  "status": 400,
  "title": " (truncated...)
  
```
The QueryBuilder alwas added the "-eq" suffix to the paramters, but for this model it is not correct. Manually executing a request like this:
GET https://***.weclapp.com/webapp/api/v1/comment?entityId=3268648&entityName=customer&pageSize=100
will bring the expected result.

This error belongs to GET and POST requests.

Any Chance to get this fixed?

BR
Frank

**Comment by Tamrael** [comment]
Sorry to get back to you so late.

I did some investigation and it seems like the endpoints "/archivedEmail", "/comment" and "/document" are the only ones that are affected and have mandatory query parameters.

I can't give you a timeline of when or if I will fix it because my company does not use these fields but if you have a solution I would be happy about a merge request.

**Comment by Nigatol** [comment]
Hi Tamrael,

No problem about the long response time, the day-to-day business eats you up.
I'm not sure if my insight into Eloquent is enough for that. 
If there will be an update on this, i am definitely interested to test it and give feedback.

Best regards
Frank

**Comment by Tamrael** [comment]
I think the latest version should now be able to handle the requests correctly. You will just have to use the "whereEntity" method. Hope this still is useful for you :)

**Comment by Nigatol** [comment]
Thank you very much. I'll test it as soon as possible.
